//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DAL.EntityModels.DataSources.SQLSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int idUser { get; set; }
        public string usr_FirstName { get; set; }
        public string usr_LastName { get; set; }
        public string usr_name { get; set; }
        public string usr_gender { get; set; }
        public byte usr_YrsOld { get; set; }
        public bool usr_Active { get; set; }
        public string usr_Title { get; set; }
        public int usr_Approbation { get; set; }
        public string usr_TagInit { get; set; }
        public string usr_Email { get; set; }
        public int idwrkShift { get; set; }
        public int idwrkArea { get; set; }
        public int idProfile { get; set; }
        public byte[] usr_Pass { get; set; }
        public bool usr_IsConnected { get; set; }
        public int idLoginType { get; set; }
    }
}
